modLoader="javafml"
loaderVersion="[47,)"
license="Not specified"

[[mods]]
modId="chriss_mod"
version="1.0.0"
displayName="Chris`s Mod"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="xristos, MCreator"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.chriss_mod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"



